export const ROOM_SELECTED = 'ROOM_SELECTED';
export const ITEM_LOG_ADDED = 'ITEM_LOG_ADDED';
export const INITIAL_DATA_LOADED = 'INITIAL_DATA_LOADED';
export const CLEAR_ROOMS_FILTER = 'CLEAR_ROOMS_FILTER';
export const ITEMS_ARE_SUSPICIOUS = 'ITEMS_ARE_SUSPICIOUS';
